### ISSUE TITLE
PHP version is 5.3 even though config is set to 5.5 (default Ubuntu configuration)

### ISSUE THREAD

**Issue by deb0rian** [protobox/protobox#109]
Hi,

Seems like it's not very clear how to install PHP 5.5 on a default configuration built on your website.

Here's my config
![91l9_yml](https://cloud.githubusercontent.com/assets/3274952/3228272/39a6132a-f085-11e3-9816-66887f6d986e.png)

**Comment by patrickheeney** [comment]
New version #155 will allow any [ansible galaxy playbooks](https://galaxy.ansible.com/explore#/). I believe we should have access to some better php playbooks to make this a better user experience.
