### ISSUE TITLE
Add support for Rails application server (Passenger, Unicorn, Puma, etc.)

### ISSUE THREAD

**Issue by zacwasielewski** [protobox/protobox#115]
This is a feature request:

Rub on Rails apps won't run out-of-the-box with Protobox because Rails requires an application server such as [Phusion Passenger](http://stackoverflow.com/a/4113570/5630).

I've poked around trying to integrate the [ansible-passenger](https://github.com/mtpereira/ansible-passenger) role, but haven't been able to make it work yet. It would be very, very awesome if Protobox supported this!

(Passenger runs as an Nginx or Apache module, so integrating it may be more complicated than a standalone Ansible role.)

**Comment by patrickheeney** [comment]
New version #155 will allow any [ansible galaxy playbooks](https://galaxy.ansible.com/explore#/) so we can work with that one directly.
