### ISSUE TITLE
Direct playbook/Vagrantfile modification?

### ISSUE THREAD

**Issue by wizonesolutions** [protobox/protobox#119]
I'm trying to figure out how to add my own shell script to do some of the provisioning (the Git repo thing) that I am not managing to do via Protobox currently for one reason or another. My first thought was to add a command to the playbook, but this seems to be generated by Protobox automatically, so it would get overwritten.

Then I thought I could just do a quick shell script, but this would have to be configured in the Vagrantfile, and I'm not sure if Protobox supports user configuration of the Vagrantfile at all?

**Comment by patrickheeney** [comment]
New version #155 will allow any [ansible galaxy playbooks](https://galaxy.ansible.com/explore#/) so you can pass in your own playbook. Alternatively it will support pre/post shell scripts.

**Comment by wizonesolutions** [comment]
Those are roles, but that is cool :)

**Comment by patrickheeney** [comment]
Good catch, you are a pro now!
