### ISSUE TITLE
File permissions and other NFS issues

### ISSUE THREAD

**Issue by EHLOVader** [protobox/protobox#138]
NFS is keeping me from updating the owner of the files within the webroot. I am looking into options for this but cannot find any configuration options yet. 

Is it possible to change the owner of the folder on the server to match that of PHP? Currently it is failing when trying to upload files and may be mildly related to the issue # 134 where the tarball extraction was failing on chown too.

One option I have discovered is the use of bindfs but it doesn't seem to be the best option available upon initial inspection. Currently it seems it may work. However the performance is really poor so far.

**Comment by patrickheeney** [comment]
Your PR fixed this I believe.
