### ISSUE TITLE
ngrok: no authtoken option for more advanced features.

### ISSUE THREAD

**Issue by EHLOVader** [protobox/protobox#141]
ngrok provides some features only to those who sign up, and even more to those who pay for the service.

There should be an `-authtoken` param passed in order to use subdomains, tcp tunnels, multiple tunnels, and password protection.

More can be found in the [ngrok features](https://ngrok.com/features)

**Comment by patrickheeney** [comment]
New version #155 will allow any [ansible galaxy playbooks](https://galaxy.ansible.com/explore#/) so hopefully will have better access to some other playbooks.
