### ISSUE TITLE
Add support for phinx.

### ISSUE THREAD

**Issue by EHLOVader** [protobox/protobox#144]
[Phinx](http://phinx.org/) is a database migration utility for PHP and can be installed through composer.

I believe this is installed much like composer was, but I did this to enable it and add it to the system path.

```
composer global require "robmorgan/phinx:*"
export PATH=$PATH:/home/vagrant/.composer/vendor/bin
```

**Comment by patrickheeney** [comment]
New version #155 will allow any [ansible galaxy playbooks](https://galaxy.ansible.com/explore#/) so I will be relying on most of them or 3rd parties to maintain the playbooks.
