### ISSUE TITLE
Whoops, looks like something went wrong.

### ISSUE THREAD

**Issue by bender-r** [protobox/protobox#163]
after click "Create Configuration File" 
Whoops, looks like something went wrong.

**Comment by isaackearl** [comment]
i can't register, or make a configuration file either.. "woops something went wrong"

**Comment by piotr-cz** [comment]
Same happens when clicking on [explore button](http://getprotobox.com/explore)

**Comment by patrickheeney** [comment]
Sorry for the troubles and the delay. It seems mysql kept crashing. It should be fixed now!

**Comment by piotr-cz** [comment]
This one still doesn't work: http://getprotobox.com/box/Dk

**Comment by patrickheeney** [comment]
@piotr-cz Fixed. Thanks again.

**Comment by manolof** [comment]
It's crashed again.

**Comment by patrickheeney** [comment]
@manolof What error do you get? The url seems to be working for me.
