### ISSUE TITLE
Add Phalcon framework support

### ISSUE THREAD

**Issue by Swader** [protobox/protobox#20]
Phalcon is a PHP extension, not a typical framework. Wrote about provisioning it with shell here: http://www.sitepoint.com/provisioning-phalcon-tools-vagrant/

Would be great if it was an option that automatically takes care of the various distros etc.

Shell provision here: https://github.com/slogsdon/vagrant-phalcon

Homepage: phalconphp.com

URL rewriting as per their documentation should also be on by default when Phalcon is selected for installation. Using it without the rewrites makes next to no sense.

**Comment by patrickheeney** [comment]
New version #155 will allow any [ansible galaxy playbooks](https://galaxy.ansible.com/explore#/).
