### ISSUE TITLE
Add Ruby version management options

### ISSUE THREAD

**Issue by ciarand** [protobox/protobox#49]
As per #47, now that we have basic Ruby functionality I think the next key step should be options for Ruby version managers. Off the top of my head I can think of [chruby][], [rvm][], and [rbenv][].

This should probably also include a Ruby builder like [ruby-build][] or [ruby-install][].

[chruby]: https://github.com/postmodern/chruby
[rvm]: http://rvm.io/
[rbenv]: https://github.com/sstephenson/rbenv
[ruby-build]: https://github.com/sstephenson/ruby-build
[ruby-install]: https://github.com/postmodern/ruby-install

**Comment by patrickheeney** [comment]
New version #155 will allow any [ansible galaxy playbooks](https://galaxy.ansible.com/explore#/). They should have a pretty feature complete playbook for ruby there I believe. If not we can look at re-opening this and building one.
